### ISSUE TITLE
Update dependencies to be dependent on latest version of travelm-agency

### ISSUE THREAD

**Issue by kraklin** [anmolitor/travelm-agency-webpack-plugin#129]
I am getting this `npm audit` error probably because the version of travelm-agency that is fixed in the package.json points to the elm 0.19.1-1 which has the dependency on vulnerable `request` library. I think that just updating the `package.json` for this plugin would solve it transitively.

![image](https://user-images.githubusercontent.com/1932160/232148919-dbe581b1-0924-4a90-b889-23d0c3044a9f.png)

**Comment by anmolitor** [comment]
I noticed that `elm` is just used for building travelm-agency, not running it (its just a compiled `index.js` afterwards),
so I moved elm to dev-dependencies which should fix the issue.

I then upgraded this plugin to travelm-agency@3.4.1, should be published in `travelm-agency-webpack-plugin@2.2.2`.
Hope this solves the issue :)

**Comment by kraklin** [comment]
Thanks @andreasewering - the issue persists, but not because of your package. I would need to dig little bit deeper on which package is downloading the elm package to node_modules. Thank you for updating this anyways 🙏
